# Generated by Django 5.2.5 on 2025-08-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaintattachment",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
