# Generated by Django 5.2.5 on 2025-08-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="PublishedAt",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="VisibleToStudent",
            field=models.BooleanField(default=False),
        ),
    ]
