# Generated by Django 5.2.5 on 2025-08-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_user_publishedat_user_visibletostudent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="PublishedAt",
        ),
        migrations.RemoveField(
            model_name="user",
            name="VisibleToStudent",
        ),
        migrations.AddField(
            model_name="response",
            name="PublishedAt",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="response",
            name="VisibleToStudent",
            field=models.BooleanField(default=False),
        ),
    ]
