# Generated by Django 5.2.5 on 2025-08-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "members",
            "0003_remove_user_publishedat_remove_user_visibletostudent_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="chatbotsession",
            name="ConversationId",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="chatbotsession",
            name="LastActivityAt",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
